// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// OrderingJosephC
List OrderingJosephC(int ind, NumericMatrix hc, List node, NumericMatrix A, NumericMatrix r, NumericMatrix maxI, NumericMatrix maxJ, CharacterVector nclass, double coef);
RcppExport SEXP ReorderCluster_OrderingJosephC(SEXP indSEXP, SEXP hcSEXP, SEXP nodeSEXP, SEXP ASEXP, SEXP rSEXP, SEXP maxISEXP, SEXP maxJSEXP, SEXP nclassSEXP, SEXP coefSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type ind(indSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type hc(hcSEXP );
        Rcpp::traits::input_parameter< List >::type node(nodeSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type r(rSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type maxI(maxISEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type maxJ(maxJSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type nclass(nclassSEXP );
        Rcpp::traits::input_parameter< double >::type coef(coefSEXP );
        List __result = OrderingJosephC(ind, hc, node, A, r, maxI, maxJ, nclass, coef);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
